-- begin FSTUDENT_USER_PROFILE
alter table FSTUDENT_USER_PROFILE add constraint FK_FSTUDENT_USER_PROFILE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table FSTUDENT_USER_PROFILE add constraint FK_FSTUDENT_USER_PROFILE_ON_SCHOOL foreign key (SCHOOL_ID) references FSTUDENT_SCHOOL(ID)^
alter table FSTUDENT_USER_PROFILE add constraint FK_FSTUDENT_USER_PROFILE_ON_MAJOR foreign key (MAJOR_ID) references FSTUDENT_MAJOR(ID)^
alter table FSTUDENT_USER_PROFILE add constraint FK_FSTUDENT_USER_PROFILE_ON_DISTRICT foreign key (DISTRICT_ID) references FSTUDENT_DISTRICT(ID)^
alter table FSTUDENT_USER_PROFILE add constraint FK_FSTUDENT_USER_PROFILE_ON_AVATAR_ID foreign key (AVATAR_ID_ID) references SYS_FILE(ID)^
create unique index IDX_FSTUDENT_USER_PROFILE_UK_USER_ID on FSTUDENT_USER_PROFILE (USER_ID) where DELETE_TS is null ^
create unique index IDX_FSTUDENT_USER_PROFILE_UK_PHONE_NUMBER on FSTUDENT_USER_PROFILE (PHONE_NUMBER) where DELETE_TS is null ^
create unique index IDX_FSTUDENT_USER_PROFILE_UK_EMAIL on FSTUDENT_USER_PROFILE (EMAIL) where DELETE_TS is null ^
create index IDX_FSTUDENT_USER_PROFILE_ON_USER on FSTUDENT_USER_PROFILE (USER_ID)^
create index IDX_FSTUDENT_USER_PROFILE_ON_SCHOOL on FSTUDENT_USER_PROFILE (SCHOOL_ID)^
create index IDX_FSTUDENT_USER_PROFILE_ON_MAJOR on FSTUDENT_USER_PROFILE (MAJOR_ID)^
create index IDX_FSTUDENT_USER_PROFILE_ON_DISTRICT on FSTUDENT_USER_PROFILE (DISTRICT_ID)^
create index IDX_FSTUDENT_USER_PROFILE_ON_AVATAR_ID on FSTUDENT_USER_PROFILE (AVATAR_ID_ID)^
-- end FSTUDENT_USER_PROFILE
-- begin FSTUDENT_PROVINCIAL
create unique index IDX_FSTUDENT_PROVINCIAL_UK_NAME on FSTUDENT_PROVINCIAL (NAME) where DELETE_TS is null ^
-- end FSTUDENT_PROVINCIAL
-- begin FSTUDENT_BOOK_CASE
alter table FSTUDENT_BOOK_CASE add constraint FK_FSTUDENT_BOOK_CASE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table FSTUDENT_BOOK_CASE add constraint FK_FSTUDENT_BOOK_CASE_ON_BOOK foreign key (BOOK_ID) references FSTUDENT_BOOK(ID)^
create index IDX_FSTUDENT_BOOK_CASE_ON_USER on FSTUDENT_BOOK_CASE (USER_ID)^
create index IDX_FSTUDENT_BOOK_CASE_ON_BOOK on FSTUDENT_BOOK_CASE (BOOK_ID)^
-- end FSTUDENT_BOOK_CASE
-- begin FSTUDENT_DISTRICT
alter table FSTUDENT_DISTRICT add constraint FK_FSTUDENT_DISTRICT_ON_PROVINCIAL foreign key (PROVINCIAL_ID) references FSTUDENT_PROVINCIAL(ID)^
create index IDX_FSTUDENT_DISTRICT_ON_PROVINCIAL on FSTUDENT_DISTRICT (PROVINCIAL_ID)^
-- end FSTUDENT_DISTRICT
-- begin FSTUDENT_BOOK
alter table FSTUDENT_BOOK add constraint FK_FSTUDENT_BOOK_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table FSTUDENT_BOOK add constraint FK_FSTUDENT_BOOK_ON_MAJOR foreign key (MAJOR_ID) references FSTUDENT_MAJOR(ID)^
alter table FSTUDENT_BOOK add constraint FK_FSTUDENT_BOOK_ON_AVATAR_ID foreign key (AVATAR_ID_ID) references SYS_FILE(ID)^
alter table FSTUDENT_BOOK add constraint FK_FSTUDENT_BOOK_ON_LINK_STORE foreign key (LINK_STORE_ID) references SYS_FILE(ID)^
create index IDX_FSTUDENT_BOOK_ON_USER on FSTUDENT_BOOK (USER_ID)^
create index IDX_FSTUDENT_BOOK_ON_MAJOR on FSTUDENT_BOOK (MAJOR_ID)^
create index IDX_FSTUDENT_BOOK_ON_AVATAR_ID on FSTUDENT_BOOK (AVATAR_ID_ID)^
create index IDX_FSTUDENT_BOOK_ON_LINK_STORE on FSTUDENT_BOOK (LINK_STORE_ID)^
-- end FSTUDENT_BOOK
-- begin FSTUDENT_SCHOOL
alter table FSTUDENT_SCHOOL add constraint FK_FSTUDENT_SCHOOL_ON_PROVINCIAL foreign key (PROVINCIAL_ID) references FSTUDENT_PROVINCIAL(ID)^
create unique index IDX_FSTUDENT_SCHOOL_UK_NAME on FSTUDENT_SCHOOL (NAME) where DELETE_TS is null ^
create index IDX_FSTUDENT_SCHOOL_ON_PROVINCIAL on FSTUDENT_SCHOOL (PROVINCIAL_ID)^
-- end FSTUDENT_SCHOOL
