alter table FSTUDENT_USER_PROFILE add constraint FK_FSTUDENT_USER_PROFILE_ON_AVATAR_ID foreign key (AVATAR_ID_ID) references SYS_FILE(ID);
create index IDX_FSTUDENT_USER_PROFILE_ON_AVATAR_ID on FSTUDENT_USER_PROFILE (AVATAR_ID_ID);
